# Be sure to restart your server when you modify this file.

# Version of your assets, change this if you want to expire all your assets.
Rails.application.config.assets.version = '1.0'

# Add additional assets to the asset load path.
# Rails.application.config.assets.paths << Emoji.images_path
# Add Yarn node_modules folder to the asset load path.
Rails.application.config.assets.paths << Rails.root.join('node_modules')

# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in the app/assets
# folder are already added.
# Rails.application.config.assets.precompile += %w( admin.js admin.css )
Rails.application.config.assets.precompile += %w( super_admins.css )
Rails.application.config.assets.precompile += %w( super_admins.js )
Rails.application.config.assets.precompile += %w( admin_application.css)
Rails.application.config.assets.precompile += %w( admin_application.js )
Rails.application.config.assets.precompile += %w( partner_application.css)
Rails.application.config.assets.precompile += %w( partner_application.js )
Rails.application.config.assets.precompile += %w( categories.css )
Rails.application.config.assets.precompile += %w( categories.js )
Rails.application.config.assets.precompile += %w( users.css )
Rails.application.config.assets.precompile += %w( users.js )
Rails.application.config.assets.precompile += %w( restaurants.css )
Rails.application.config.assets.precompile += %w( restaurants.js )
Rails.application.config.assets.precompile += %w( orders.css )
Rails.application.config.assets.precompile += %w( orders.js )
Rails.application.config.assets.precompile += %w( business/partners.css )
Rails.application.config.assets.precompile += %w( business/partners.js )
Rails.application.config.assets.precompile += %w( business/orders.css )
Rails.application.config.assets.precompile += %w( business/orders.js )
Rails.application.config.assets.precompile += %w( business/branches.css )
Rails.application.config.assets.precompile += %w( business/branches.js )
Rails.application.config.assets.precompile += %w( business/users.css )
Rails.application.config.assets.precompile += %w( business/users.js )
Rails.application.config.assets.precompile += %w( offers.css )
Rails.application.config.assets.precompile += %w( offers.js )
Rails.application.config.assets.precompile += %w(notifications.css)
Rails.application.config.assets.precompile += %w(notifications.js)
Rails.application.config.assets.precompile += %w( business/offers.css )
Rails.application.config.assets.precompile += %w( business/offers.js )
Rails.application.config.assets.precompile += %w(reports.css)
Rails.application.config.assets.precompile += %w(reports.js)
Rails.application.config.assets.precompile += %w( business/reports.css )
Rails.application.config.assets.precompile += %w( business/reports.js )
Rails.application.config.assets.precompile += %w( business/notifications.css )
Rails.application.config.assets.precompile += %w( business/notifications.js )
Rails.application.config.assets.precompile += %w( clubes.css )
Rails.application.config.assets.precompile += %w( clubes.js )
Rails.application.config.assets.precompile += %w( appsettings.css )
Rails.application.config.assets.precompile += %w( appsettings.js )
Rails.application.config.assets.precompile += %w( documents.css )
Rails.application.config.assets.precompile += %w( documents.js )
Rails.application.config.assets.precompile += %w( business/documents.css )
Rails.application.config.assets.precompile += %w( business/documents.js )
Rails.application.config.assets.precompile += %w( business/budgets.css )
Rails.application.config.assets.precompile += %w( business/budgets.js )
Rails.application.config.assets.precompile += %w( reviews.css )
Rails.application.config.assets.precompile += %w( reviews.js )
Rails.application.config.assets.precompile += %w( business/ious.css )
Rails.application.config.assets.precompile += %w( business/ious.js )
Rails.application.config.assets.precompile += %w( business/categories.css )
Rails.application.config.assets.precompile += %w( business/categories.js )
Rails.application.config.assets.precompile += %w( areas.css )
Rails.application.config.assets.precompile += %w( areas.js )
Rails.application.config.assets.precompile += %w(subscriptions.css)
Rails.application.config.assets.precompile += %w(subscriptions.js)
Rails.application.config.assets.precompile += %w(ckeditor/*)
Rails.application.config.assets.precompile += %w( check_styles.css business/hrms.css )
