production:
  imagekit_private_key: <%= ENV['IMAGEKIT_PRIVATE_KEY'] %>
  imagekit_public_key: <%= ENV['IMAGEKIT_PUBLIC_KEY'] %>
  imagekit_url_endpoint: <%= ENV['IMAGEKIT_URL_ENDPOINT'] %>
  ocr_api_key: <%= ENV['OCR_API_KEY'] %>
  ocr_space_url: <%= ENV['OCR_SPACE_URL'] %>
